INSERT INTO task_templates (id, section, title, description, tips, resources, order_index) VALUES
('foundry_1', 'foundry', 'Choose Business Name', 'Research your desired name on your state''s business registry and do a trademark search.', 'Check trademark availability at USPTO and domain availability before finalizing.', '[{"label": "USPTO Trademark Search", "url": "https://www.uspto.gov/trademarks/search"}]', 1),
('foundry_2', 'foundry', 'Obtain Registered Agent', 'Get a registered agent for privacy protection and compliance.', 'I personally recommend ZenBusiness. You don''t have to purchase upsells.', '[{"label": "ZenBusiness", "url": "https://www.zenbusiness.com"}]', 2),
('foundry_3', 'foundry', 'Get Physical Business Address', 'Obtain a real street address (not PO Box). Use a virtual office for privacy.', 'Regus virtual office recommended. Call (800) 633-4237 for discounts.', '[{"label": "Regus", "url": "https://www.regus.com"}]', 3),
('foundry_4', 'foundry', 'Register LLC/Corporation', 'File formation documents through your Secretary of State.', 'Free with funding package or use Incfile/LegalZoom.', '[{"label": "Incfile", "url": "https://www.incfile.com"}]', 4),
('foundry_5', 'foundry', 'Obtain EIN', 'Apply for your Employer Identification Number at IRS.gov - free and takes minutes.', 'An EIN is like a social security number for your business.', '[{"label": "IRS EIN Application", "url": "https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online"}]', 5),
('foundry_6', 'foundry', 'Get Business Phone (800 Number)', 'Get a dedicated 800 business number for professional credibility.', 'Use code 0SETUP at Kall8 for discount.', '[{"label": "Kall8", "url": "https://signup.kall8.com"}]', 6),
('foundry_7', 'foundry', 'Find NAICS Code', 'Identify your 6-digit industry classification code.', 'Use consulting/marketing code (541613) - viewed as low-risk by lenders.', '[{"label": "NAICS Lookup", "url": "https://www.naics.com"}]', 7),
('foundry_8', 'foundry', 'Obtain Business License', 'Check if your city/county/state requires a general business license.', 'Requirements vary by location and industry.', '[{"label": "SBA License Lookup", "url": "https://www.sba.gov/business-guide/launch-your-business/apply-licenses-permits"}]', 8),
('foundry_9', 'foundry', 'Draft Operating Agreement', 'Create and sign your LLC operating agreement.', 'Required in most states. Outlines member responsibilities.', '[]', 9),
('identity_1', 'identity', 'Obtain D-U-N-S Number', 'Apply for free D-U-N-S at dnb.com. Essential for D&B business credit.', 'D&B may call to upsell - purchasing is NOT required.', '[{"label": "D&B D-U-N-S", "url": "https://www.dnb.com/duns-number.html"}]', 1),
('identity_2', 'identity', 'Register with Experian Business', 'Create your Experian Business credit profile.', 'Your business credit is separate from personal credit.', '[{"label": "Experian Business", "url": "https://smallbusiness.experian.com"}]', 2),
('identity_3', 'identity', 'Register with Equifax Business', 'Set up your Equifax Business credit profile.', 'Having profiles with all three bureaus gives lenders a complete picture.', '[{"label": "Equifax Business", "url": "https://www.equifax.com/business"}]', 3),
('identity_4', 'identity', 'Register Domain Name', 'Purchase yourbusiness.com domain ($10-15/year).', 'A custom domain makes your business look serious.', '[{"label": "Namecheap", "url": "https://www.namecheap.com"}]', 4),
('identity_5', 'identity', 'Set Up Business Email', 'Create yourname@yourbusiness.com using Google Workspace (~$6/month).', 'A professional email looks far more credible on applications.', '[{"label": "Google Workspace", "url": "https://workspace.google.com"}]', 5),
('identity_6', 'identity', 'Create Business Logo', 'Get a professional logo from Fiverr ($5-50).', 'A logo solidifies your brand identity.', '[{"label": "Fiverr", "url": "https://www.fiverr.com"}]', 6),
('identity_7', 'identity', 'Build Business Website', 'Create at least a one-page site with company overview and contact info.', 'Lenders WILL Google your business.', '[{"label": "Wix", "url": "https://www.wix.com"}]', 7),
('identity_8', 'identity', 'Google Business Profile', 'Claim and verify your Google Business listing.', 'Appear on Google Maps and search results.', '[{"label": "Google Business", "url": "https://business.google.com"}]', 8),
('identity_9', 'identity', 'Register with 411 Directory', 'Add your business to 411 at ListYourself.net (free).', 'Many VoIP providers don''t automatically list numbers.', '[{"label": "ListYourself", "url": "https://www.listyourself.net"}]', 9),
('identity_10', 'identity', 'Yelp Business Page', 'Claim and complete your Yelp business profile.', 'Ensure NAP is identical across ALL listings.', '[{"label": "Yelp", "url": "https://biz.yelp.com"}]', 10),
('identity_11', 'identity', 'LinkedIn Company Page', 'Create a LinkedIn Company Page.', 'Essential for B2B credibility.', '[{"label": "LinkedIn", "url": "https://www.linkedin.com/company/setup/new/"}]', 11),
('treasury_chase_1', 'treasury', 'Chase - Personal Checking', 'Open Chase personal checking ($50 min deposit).', 'Chase relationship banking unlocks business lines.', '[]', 1),
('treasury_chase_2', 'treasury', 'Chase - Personal Savings', 'Open Chase personal savings ($50 min deposit).', 'Building a relationship with Chase is essential.', '[]', 2),
('treasury_chase_3', 'treasury', 'Chase - Business Checking', 'Open Chase business checking. Requires EIN & LLC docs.', 'Prioritize Chase early in your journey.', '[]', 3),
('treasury_chase_4', 'treasury', 'Chase - Business Savings', 'Open Chase business savings ($50 min deposit).', 'Complete all four account types for maximum value.', '[]', 4),
('treasury_bofa_1', 'treasury', 'Bank of America - Personal Checking', 'Open BofA personal checking.', 'Strong business credit reporting partner.', '[]', 5),
('treasury_bofa_2', 'treasury', 'Bank of America - Personal Savings', 'Open BofA personal savings.', 'BofA offers secured business cards.', '[]', 6),
('treasury_bofa_3', 'treasury', 'Bank of America - Business Checking', 'Open BofA business checking.', 'Reports to business credit bureaus.', '[]', 7),
('treasury_bofa_4', 'treasury', 'Bank of America - Business Savings', 'Open BofA business savings.', 'Build the full relationship.', '[]', 8),
('treasury_wells_1', 'treasury', 'Wells Fargo - Personal Checking', 'Open Wells Fargo personal checking.', 'Conservative bank. Good for stability.', '[]', 9),
('treasury_wells_2', 'treasury', 'Wells Fargo - Personal Savings', 'Open Wells Fargo personal savings.', 'Good for relationship banking.', '[]', 10),
('treasury_wells_3', 'treasury', 'Wells Fargo - Business Checking', 'Open Wells Fargo business checking.', 'Solid option for business banking.', '[]', 11),
('treasury_wells_4', 'treasury', 'Wells Fargo - Business Savings', 'Open Wells Fargo business savings.', 'Complete the full relationship.', '[]', 12),
('treasury_citi_1', 'treasury', 'Citi - Personal Checking', 'Open Citi personal checking.', 'Good for accessing Citi Business Credit Cards.', '[]', 13),
('treasury_citi_2', 'treasury', 'Citi - Business Checking', 'Open Citi business checking.', 'Great for international business needs.', '[]', 14),
('treasury_acc_1', 'treasury', 'Join American Consumer Council', 'Sign up at americanconsumercouncil.org - Use code "Andrews".', 'ACC membership unlocks access to many credit unions.', '[{"label": "ACC", "url": "https://www.americanconsumercouncil.org"}]', 15),
('treasury_navyfed_1', 'treasury', 'Navy Federal - Accounts', 'Open Navy Federal accounts if military affiliated.', 'Known for aggressive high-limit approvals.', '[{"label": "Navy Federal", "url": "https://www.navyfederal.org"}]', 16),
('treasury_penfed_1', 'treasury', 'PenFed - Accounts', 'Open PenFed accounts.', 'Open to all with small donation.', '[{"label": "PenFed", "url": "https://www.penfed.org"}]', 17),
('creditcore_1', 'credit_core', 'Set Up Nav Monitoring', 'Use Nav.com to monitor D&B, Experian, and Equifax business credit.', 'Nav paid plans report a tradeline on your behalf.', '[{"label": "Nav.com", "url": "https://www.nav.com"}]', 1),
('creditcore_2', 'credit_core', 'Sign Up for D&B CreditSignal', 'Get free alerts when your D&B scores change.', 'Monitor your PAYDEX and other D&B ratings.', '[{"label": "D&B CreditSignal", "url": "https://www.dnb.com/products/small-business/creditsignal.html"}]', 2),
('creditcore_3', 'credit_core', 'Net-30: Uline', 'Open Uline Net-30 account (shipping/office supplies). Reports to D&B.', 'Common easy-approval vendor.', '[{"label": "Uline", "url": "https://www.uline.com"}]', 3),
('creditcore_4', 'credit_core', 'Net-30: Quill', 'Open Quill Net-30 account (office supplies).', 'Start with small orders.', '[{"label": "Quill", "url": "https://www.quill.com"}]', 4),
('creditcore_5', 'credit_core', 'Net-30: Grainger', 'Open Grainger Net-30 account (industrial supplies).', 'Industrial supplies vendor. Reports to D&B.', '[{"label": "Grainger", "url": "https://www.grainger.com"}]', 5),
('creditcore_6', 'credit_core', 'Net-30: Account #4', 'Open fourth Net-30 vendor account.', 'Research vendors in your industry.', '[]', 6),
('creditcore_7', 'credit_core', 'Net-30: Account #5', 'Open fifth Net-30 vendor account.', 'Aim for 5+ Net-30 accounts.', '[]', 7),
('creditcore_8', 'credit_core', 'Business Credit Card #1', 'Apply for first business credit card.', 'Start secured if needed.', '[]', 8),
('creditcore_9', 'credit_core', 'Business Credit Card #2', 'Apply for second business credit card.', 'Multiple cards diversify your credit mix.', '[]', 9),
('creditcore_10', 'credit_core', 'Pledge/Secured Loan', 'Apply for a pledge loan from a credit union.', 'Installment loans diversify your credit mix.', '[]', 10),
('creditcore_11', 'credit_core', 'Achieve 80 PAYDEX Score', 'Build to 80+ PAYDEX by paying Net-30 accounts on time.', '80 PAYDEX = pay on time. 100 = pay 30+ days early.', '[]', 11),
('creditcore_12', 'credit_core', 'Reach 11 Total Credit Lines', 'Build to 11 total credit accounts.', 'Credit mix affects creditworthiness.', '[]', 12),
('control_1', 'control', 'Keep Utilization Under 30%', 'Maintain credit card balances below 30% of limits.', 'Lower utilization = higher scores. Aim for under 10%.', '[]', 1),
('control_2', 'control', 'Pay Balances Early/Full', 'Pay credit card balances in full or before statement closes.', 'Paying before statement close reports $0 balance.', '[]', 2),
('control_3', 'control', 'Set Payment Reminders', 'Set up automatic payments or reminders.', 'Payment history is the most important factor.', '[]', 3),
('control_4', 'control', 'Keep Old Accounts Open', 'Maintain older accounts for credit history length.', 'Average age of accounts matters.', '[]', 4),
('control_5', 'control', 'Monitor Credit Reports', 'Check all three bureaus monthly.', 'Errors can hurt your score. Dispute inaccuracies.', '[]', 5),
('control_6', 'control', 'Request Credit Limit Increases', 'Request increases every 6-12 months.', 'Higher limits with same spending = lower utilization.', '[]', 6),
('command_1', 'command', 'Use Nav Monitoring Tool', 'Maintain active Nav.com subscription.', 'Continuous monitoring catches issues early.', '[{"label": "Nav.com", "url": "https://www.nav.com"}]', 1),
('command_2', 'command', 'Keep Financial Statements Updated', 'Maintain current P&L and balance sheet.', 'Lenders may request financials.', '[]', 2),
('command_3', 'command', 'Stay Current with Tax Filings', 'File all business taxes on time.', 'Tax compliance is essential.', '[]', 3),
('command_4', 'command', 'Show Consistent Revenue', 'Demonstrate consistent or growing revenue.', 'Revenue trends affect lending decisions.', '[]', 4),
('command_5', 'command', 'Annual Report Filings', 'File required annual reports with your state.', 'Missing annual reports can dissolve your LLC.', '[]', 5),
('command_6', 'command', 'License Renewals', 'Track and renew all business licenses.', 'Set calendar reminders for deadlines.', '[]', 6),
('vault_id', 'the_vault', 'Government-Issued ID', 'Upload a clear photo of your ID (front and back).', 'Ensure text is clearly readable.', '[]', 1),
('vault_ssn', 'the_vault', 'Social Security Card', 'Upload your Social Security card.', 'Keep this document secure.', '[]', 2),
('vault_address', 'the_vault', 'Proof of Address', 'Upload a utility bill or bank statement dated within 60 days.', 'Must show your current address.', '[]', 3),
('vault_ein', 'the_vault', 'EIN Confirmation Letter', 'Upload your IRS EIN confirmation letter (CP 575 or 147C).', 'Save this letter - you''ll use it often.', '[]', 4),
('vault_llc', 'the_vault', 'LLC Formation Documents', 'Upload your Articles of Organization.', 'Proves your business is legally registered.', '[]', 5),
('vault_operating', 'the_vault', 'Operating Agreement', 'Upload your signed LLC Operating Agreement.', 'Required by most states for LLCs.', '[]', 6),
('vault_license', 'the_vault', 'Business License', 'Upload your business license if applicable.', 'Not all businesses require a license.', '[]', 7);

INSERT INTO survey_questions (id, section, question, options, order_index) VALUES
('survey_treasury_military', 'treasury', 'Do you or a family member have military affiliation?', '[{"value": "yes", "label": "Yes"}, {"value": "no", "label": "No"}]', 1),
('survey_treasury_existing', 'treasury', 'Do you have existing business bank accounts?', '[{"value": "yes", "label": "Yes"}, {"value": "no", "label": "No"}]', 2),
('survey_identity_website', 'identity', 'Do you already have a business website?', '[{"value": "yes", "label": "Yes"}, {"value": "no", "label": "No"}]', 1);
